-- Drop old Manus OAuth columns
ALTER TABLE users DROP COLUMN IF EXISTS openId;
ALTER TABLE users DROP COLUMN IF EXISTS loginMethod;

-- Add new custom auth columns if they don't exist
ALTER TABLE users ADD COLUMN IF NOT EXISTS passwordHash VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INT NOT NULL DEFAULT 18;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS isAgeVerified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS acceptedTerms BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS language ENUM('en', 'hi', 'ta', 'te', 'mr') NOT NULL DEFAULT 'en';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profilePicture TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS totalPoints INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totalTeams INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emailVerified BOOLEAN NOT NULL DEFAULT FALSE;

-- Modify email to be NOT NULL and UNIQUE
ALTER TABLE users MODIFY COLUMN email VARCHAR(320) NOT NULL;
ALTER TABLE users ADD UNIQUE INDEX IF NOT EXISTS email_unique (email);

-- Modify name to be NOT NULL
ALTER TABLE users MODIFY COLUMN name TEXT NOT NULL;
